### PR TITLE
skopeo: support copy to OSTree storage

### PR DESCRIPTION
**Pull request by giuseppe**
Currently blocked on: https://github.com/containers/image/pull/228

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
ACK on the skopeo parts

**Comment by giuseppe** [comment]
@mtrmac I have updated `containers/image` and amended in the patch

**Comment by runcom** [comment]
why is github always saying branch is out-of-date :confused:

**Comment by mtrmac** [comment]
LGTM, for the record.

> why is github always saying branch is out-of-date 😕

Well, because it is? Giuseppe, please rebase on top of current master and we’ll merge.

**Comment by runcom** [comment]
Of course, I thought it was like the last time in c/image eheh

**Comment by giuseppe** [comment]
@mtrmac @runcom I've rebased and pushed the new version

**Pull request merged**
