### PR TITLE
Re-vendor, primarily for https://github.com/containers/storage/pull/11

### PR DESCRIPTION
**Pull request by mtrmac**
containers/storage got new dependencies, so we will need to re-vendor eventually anyway, and having this separate from other major work is cleaner.

But the primary goal of this commit is to see whether it makes skopeo buildable on OS X.

### CODE REVIEW

**Comment by runcom** [comment]
`make check` failed

**Comment by mtrmac** [comment]
Yeah, I somehow managed to persuade git that there is a submodule. Hopefully fixed.

(And no, we can’t trivially add a macOS target to Travis CI, because Travis does not support Docker on macOS. I suppose we could test `make binary-local` at least… but I’ll leave that to someone actually using macOS for skopeo development.)

**Comment by mtrmac** [comment]
@runcom tests pass now.

**Comment by runcom** [comment]
is there anyone willing to give this a try for MacOS? @hferentschik perhaps?

**Pull request merged**
