### PR TITLE
update installing build dependencies

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by runcom** [comment]
LGTM :)

**Comment by TomSweeneyRedHat** [comment]
LGTM. The changes look fine, but we may have dependency issues.  I tried building with the old and new instructions and got the same nastiness below.

[root@localhost skopeo]# cd $GOPATH/src/github.com/projectatomic/skopeo 
[root@localhost skopeo]# make binary-local
go build -ldflags "-X main.gitCommit=09557f308ca29204842f885946767e0da2e61c0b" -gcflags "" -tags "  " -o skopeo ./cmd/skopeo
cmd/skopeo/copy.go:9:2: cannot find package "github.com/containers/image/copy" in any of:
	/usr/lib/golang/src/github.com/containers/image/copy (from $GOROOT)
	/root/go/src/github.com/containers/image/copy (from $GOPATH)
cmd/skopeo/layers.go:9:2: cannot find package "github.com/containers/image/directory" in any of:
	/usr/lib/golang/src/github.com/containers/image/directory (from $GOROOT)
	/root/go/src/github.com/containers/image/directory (from $GOPATH)
cmd/skopeo/inspect.go:9:2: cannot find package "github.com/containers/image/docker" in any of:
	/usr/lib/golang/src/github.com/containers/image/docker (from $GOROOT)
	/root/go/src/github.com/containers/image/docker (from $GOPATH)
cmd/skopeo/layers.go:10:2: cannot find package "github.com/containers/image/image" in any of:
	/usr/lib/golang/src/github.com/containers/image/image (from $GOROOT)
	/root/go/src/github.com/containers/image/image (from $GOPATH)
cmd/skopeo/inspect.go:10:2: cannot find package "github.com/containers/image/manifest" in any of:
	/usr/lib/golang/src/github.com/containers/image/manifest (from $GOROOT)
	/root/go/src/github.com/containers/image/manifest (from $GOPATH)
cmd/skopeo/main.go:7:2: cannot find package "github.com/containers/image/signature" in any of:
	/usr/lib/golang/src/github.com/containers/image/signature (from $GOROOT)
	/root/go/src/github.com/containers/image/signature (from $GOPATH)
cmd/skopeo/copy.go:10:2: cannot find package "github.com/containers/image/transports" in any of:
	/usr/lib/golang/src/github.com/containers/image/transports (from $GOROOT)
	/root/go/src/github.com/containers/image/transports (from $GOPATH)
cmd/skopeo/copy.go:11:2: cannot find package "github.com/containers/image/transports/alltransports" in any of:
	/usr/lib/golang/src/github.com/containers/image/transports/alltransports (from $GOROOT)
	/root/go/src/github.com/containers/image/transports/alltransports (from $GOPATH)
cmd/skopeo/copy.go:12:2: cannot find package "github.com/containers/image/types" in any of:
	/usr/lib/golang/src/github.com/containers/image/types (from $GOROOT)
	/root/go/src/github.com/containers/image/types (from $GOPATH)
cmd/skopeo/main.go:8:2: cannot find package "github.com/containers/storage/pkg/reexec" in any of:
	/usr/lib/golang/src/github.com/containers/storage/pkg/reexec (from $GOROOT)
	/root/go/src/github.com/containers/storage/pkg/reexec (from $GOPATH)
cmd/skopeo/inspect.go:12:2: cannot find package "github.com/opencontainers/go-digest" in any of:
	/usr/lib/golang/src/github.com/opencontainers/go-digest (from $GOROOT)
	/root/go/src/github.com/opencontainers/go-digest (from $GOPATH)
cmd/skopeo/inspect.go:13:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/lib/golang/src/github.com/pkg/errors (from $GOROOT)
	/root/go/src/github.com/pkg/errors (from $GOPATH)
cmd/skopeo/main.go:9:2: cannot find package "github.com/projectatomic/skopeo/version" in any of:
	/usr/lib/golang/src/github.com/projectatomic/skopeo/version (from $GOROOT)
	/root/go/src/github.com/projectatomic/skopeo/version (from $GOPATH)
cmd/skopeo/inspect.go:14:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/lib/golang/src/github.com/sirupsen/logrus (from $GOROOT)
	/root/go/src/github.com/sirupsen/logrus (from $GOPATH)
cmd/skopeo/copy.go:13:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/golang/src/github.com/urfave/cli (from $GOROOT)
	/root/go/src/github.com/urfave/cli (from $GOPATH)
make: *** [Makefile:66: binary-local] Error 1

**Comment by TomSweeneyRedHat** [comment]
Changing this to LGTM period.  The issue that I showed in my previous comment was caused by cockpit error.  I'd badly mangled my GOPATH environment variable.  We've no build dependency issues in skopeo.

**Comment by mtrmac** [comment]
What is the precise reason for this change?

Sure, the command is shorter, but there’s no guarantee that the set of dependencies needed by the user’s checkout of the skopeo git will match the set of dependencies needed by Fedora’s currently packaged version of skopeo.

**Comment by thomasmckay** [comment]
On F26, I tried following the existing instructions and got this
```
$ make binary-local
go build -ldflags "-X main.gitCommit=09557f308ca29204842f885946767e0da2e61c0b" -gcflags "" -tags "  " -o skopeo ./cmd/skopeo
# pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'ostree-1', required by 'virtual:world', not found
Package 'ostree-1', required by 'virtual:world', not found
Package 'ostree-1', required by 'virtual:world', not found
Package 'ostree-1', required by 'virtual:world', not found
Package 'ostree-1', required by 'virtual:world', not found
Package 'ostree-1', required by 'virtual:world', not found
pkg-config: exit status 1
make: *** [Makefile:66: binary-local] Error 2
```
Running _dnf builddep skopeo_ allowed the build to run successfully.

I don't know the correct instructions but what is there now seems incomplete.

**Comment by mtrmac** [comment]
Good catch, the command is missing `ostree-devel`.

**Comment by thomasmckay** [comment]
updated to simply include ostree-devel

**Comment by mtrmac** [comment]
Thanks!

**Pull request merged**
