### PR TITLE
vendor: bump containers/image and containers/image

### PR DESCRIPTION
**Pull request by giuseppe**
Update containers/image and containers/storage to the current master
revisions.

So to inherit all the fixes in the ostree backend.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
Sure, LGTM pending tests.

**Comment by giuseppe** [comment]
hm.. the CI is still running

**Comment by runcom** [comment]
restarted, LGTM

**Comment by mtrmac** [comment]
@runcom Can you restart the tests again, please? (Is it something I can do as well?)

**Comment by runcom** [comment]
> Is it something I can do as well?)

I go to Travis and just click Cancel build, then Rebuild

**Pull request merged**
