### PR TITLE
vendor containers/image 5c10ea7c3f0b1f2e36164c15667cc847b1784e16

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@mtrmac FYI https://github.com/docker/docker/pull/24213

**Comment by mtrmac** [comment]
> @mtrmac FYI docker/docker#24213

Cool, thanks!

This looks fairly big; what does this do to `skopeo` binary size? In any case, whatever the number is, LGTM to merge.

**Comment by runcom** [comment]
> This looks fairly big; what does this do to skopeo binary size?

I'll try and report some numbers in a moment but getting rid of a forked piece of code is somehow worth the additional memory mapping during a skopeo run :cry:

**Comment by mtrmac** [comment]
Sure, as I said, LGTM whatever the result is.

**Comment by runcom** [comment]
green \o/ merging

**Pull request merged**
