### PR TITLE
Move copy implementation into containers/image

### PR DESCRIPTION
**Pull request by mtrmac**
This pulls in https://github.com/containers/image/pull/56 and updates the API usage.

Depends on way too much pending work, I will rebase as necessary.

### CODE REVIEW

**Comment by mtrmac** [comment]
Reconstructed to depend only on #180 (and the containers/image PR).

**Comment by runcom** [comment]
#180 merged

**Comment by mtrmac** [comment]
Yeah, this contains a few changes which are not purely re-vendoring + API changes so I was thinking you might want to give this a quick look over.

**Comment by mtrmac** [comment]
… oops, I didn’t push the rebased branch. Pushed now, I will revendor to containers/image:master in the mean time.

**Comment by runcom** [comment]
I'll take a look sure!

**Comment by runcom** [comment]
LGTM, merging

**Pull request merged**
