### PR TITLE
vendor: update containers/image@fb36437

### PR DESCRIPTION
**Pull request by cyphar**
This change includes the docker-archive: transport, allowing for
entirely local manipulation of Docker images.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM if tests green!

**Comment by cyphar** [comment]
I'll get to work on the various `docker-archive:` tests as soon as I can.

**Comment by mtrmac** [comment]
Thanks!

**Comment by cyphar** [comment]
@runcom @mtrmac Is there a chance we can tag a release before we get v1.0.0-rc5 in? I can do it specifically for us, but since `umoci` and a bunch of other tools still haven't swapped to `v1.0.0-rc5` it'd be nice to have a "proper `v1.0.0-rc3` version" that can be maintained until everyone is updated to `v1.0.0-rc5`? WDYT?

**Comment by runcom** [comment]
@cyphar sure, I can tag v0.1.19 this evening (my tmz)

**Pull request merged**
