### PR TITLE
containers/image: vendor

### PR DESCRIPTION
**Pull request by giuseppe**
Vendor in latest containers/image

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by ashcrow** [comment]
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1499274

**Comment by runcom** [comment]
LGTM (assuming Travis is ok)

**Comment by giuseppe** [comment]
@ashcrow good catch.  I've updated my vndr and now vendor.conf is not deleted.

**Comment by ashcrow** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by giuseppe** [comment]
tests are passing

**Pull request merged**
