### PR TITLE
Vendor containers/storage

### PR DESCRIPTION
**Pull request by nalind**
Vendor containers/storage, and its dependencies github.com/mistifyio/go-zfs and github.com/pborman/uuid.

### CODE REVIEW

**Comment by mtrmac** [comment]
I guess it would be cleanest to have a single PR which vendors this as one commit, and then the appropriate version of `containers/image` as another commit.  In the meantime, is there a benefit? Am I right in guessing that it would allow the https://github.com/containers/image/pull/63 tests to pass?

**Comment by nalind** [comment]
This should fix most of the problem that's keeping the test for containers/image#63 from passing, but I think it still needs to conditionally define the _btrfs_noversion_ and _libdm_no_deferred_remove_ build tags.

**Comment by rhatdan** [comment]
Is this still being worked on?

**Comment by nalind** [comment]
@rhatdan Yes, the PR is current.

**Comment by rhatdan** [comment]
@mtrmac @runcom PTAL

**Comment by runcom** [comment]
@rhatdan we need to first merge https://github.com/containers/image/pull/63 and that's pending review by Miloslav

**Comment by rhatdan** [comment]
Ok we just need him to make sure nothing in Signatures gets broken.

**Comment by nalind** [comment]
Updated to pull in the current version of containers/image as well.

**Pull request merged**
