### PR TITLE
Add pkg/errors dependency

### PR DESCRIPTION
**Pull request by tscolari**
Required for https://github.com/containers/image/pull/182

Signed-off-by: Claudia Beresford <cberesford@pivotal.io>

### CODE REVIEW

**Comment by runcom** [comment]
@tscolari in order to vendor a dependency here you first have to vendor the code which actually uses it. In this case https://github.com/containers/image/pull/182.
You need to edit `hack/vendor.sh` and add a line to vendor `pkg/errors` + you need to modify the `containers/image` line to vendor from `docker-src-error-wrap` branch from `https://github.com/tscolari/image`, then run `hack/vendor.sh`. After https://github.com/containers/image/pull/182 is merged you'll move `containers/image` back to `master`, run `hack/vendor.sh` again and this PR will be good to be reviewed and merged.

**Comment by glestaris** [comment]
Updated after changes in https://github.com/containers/image/pull/186 and rebased.

**Comment by runcom** [comment]
@glestaris could you run `./hack/vendor.sh` one more time w/ the correct containers/image ref? Thanks!

**Comment by glestaris** [comment]
I switched back to `containers/image` master @runcom. Should now be good to merge.

**Pull request merged**
