### PR TITLE
Rename type insecureAcceptAnything to accept

### PR DESCRIPTION
**Pull request by aweiteka**
Required for pending change in upstream library https://github.com/containers/image/pull/132

Signed-off-by: Aaron Weitekamp aweiteka@redhat.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Don't we need to get this into skopeo before we ship rhel7.3.1?

**Comment by aweiteka** [comment]
We need this in https://github.com/containers/image/pull/132 first, then this can go in. We can stage support in (atomic CLI)[https://github.com/projectatomic/atomic/blob/master/Atomic/trust.py] so it will be backwards compatible.

**Comment by rhatdan** [comment]
Is this pull request still something we are considering?

**Comment by aweiteka** [comment]
At this point I consider skopeo an "expert" tool so I'm okay just mapping this to 'accept' in atomic CLI or any other tools that call/wrap skopeo.

**Comment by rhatdan** [comment]
Then can you close this pull request.

**Pull request closed without merging**
