### PR TITLE
Add policy configuration data structures, construction and parsing

### PR DESCRIPTION
**Pull request by mtrmac**
There are a few outstanding FIXMEs, but otherwise this should be pretty feature-complete, if anyone wanted to review this now.

Depends on / includes #54, I will rebase as necessary.

### CODE REVIEW

**Comment by mtrmac** [comment]
There is nothing special in here; just a fair amount of careful parsing, and tests for it.

**Comment by runcom** [comment]
This needs a rebase - LGTM though, will merge after rebase

**Comment by mtrmac** [comment]
Thanks, for the review, I’d rather wait with merging until the implementation lands as well, in case I have missed something.

**Comment by mtrmac** [comment]
Updated: added validation of Docker Reference strings (keys in `Policy.Specific`, and references in `NewPRMExactReference` and `NewPRMExactRepository`. No further changes expected to this in the near future.

**Comment by mtrmac** [comment]
Sorry, a few more comment changes still pending.

**Comment by mtrmac** [comment]
Updated now, for real.

**Comment by runcom** [comment]
LGTM again, I like all the tests around this also, tell me if this is mergeable and I'll merge

**Comment by mtrmac** [comment]
Yes, this is mergeable. Merging to save a round-trip. Thanks for the review!

**Pull request merged**
