### PR TITLE
Update to image-spec v1.0.0 and revendor

### PR DESCRIPTION
**Pull request by mtrmac**
Update from image-spec 1.0.0rc6 to the final one.

(Yes, this does not change a single bit of the code from image-spec that we actually use, so we are updating only to look good; OTOH it does add quite a few updates from other packages. Potentially notable is that `opencontainers/go-digest` now refuses uppercase digits in digest values.)

### CODE REVIEW

**Comment by mtrmac** [comment]
@rhatdan FYI

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
Can we get this merged?

**Pull request merged**
