### PR TITLE
fail early when image os doesn't match host os

### PR DESCRIPTION
**Pull request by runcom**
vendors https://github.com/containers/image/pull/282

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
LGTM pending tests.

**Comment by runcom** [comment]
```
Running skopeo copy docker://microsoft/windowsservercore containers-storage:test
copy_test.go:95:
    assertSkopeoFails(c, `.*image operating system "windows" cannot be used on "linux".*`, "copy", "docker://microsoft/windowsservercore", "containers-storage:test")
utils.go:73:
    c.Assert(string(out), check.Matches, "(?s)"+regexp) // (?s) : '.' will also match newlines
... value string = "" +
...     "time=\"2017-06-06T11:38:14Z\" level=error msg=\"'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.\" \n" +
...     "time=\"2017-06-06T11:38:14Z\" level=fatal msg=\"Invalid destination name containers-storage:test: driver not supported\" \n"
... regex string = "(?s).*image operating system \"windows\" cannot be used on \"linux\".*"
```
we can't actually test this on Travis :confused:

**Comment by runcom** [comment]
I'm skipping the test in travis :(

**Comment by runcom** [comment]
I'll research how to enable that in Travis in a follow up. Thanks

**Pull request merged**
