### PR TITLE
Fix skopeo tests with changes to dir transport

### PR DESCRIPTION
**Pull request by umohnani8**
The dir transport has been changed to save the blobs without the .tar extension
Fixes the skopeo tests failing due to this change

Vendors in changes from https://github.com/containers/image/pull/419

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 travis isn't happy with your changes.  Looks like --tls-verify has been deprecated?

**Comment by umohnani8** [comment]
@TomSweeneyRedHat yeah it was complaining because the directories still had the blobs as digest.tar, took me a bit to figure out that I had to go change the blob names manually. The deprecated thing is just a warning.
Tests should pass now :)

**Comment by TomSweeneyRedHat** [comment]
LGTM with happy tests, and I'm betting you're right on the name change as being the culprit.

**Comment by TomSweeneyRedHat** [comment]
BTB, do you still want the "DO NOT MERGE" tag in the title?

**Comment by umohnani8** [comment]
@TomSweeneyRedHat yup, this shows that my containers/image changes is good to merge once these tests pass. Once that PR is in, I will update this and it can get merged in as well.

**Comment by mtrmac** [comment]
ACK on the tests update.

**Comment by runcom** [comment]
ACK

**Comment by umohnani8** [comment]
Changed vendor back to master. @mtrmac @runcom ready to merge once tests are green :)

**Pull request merged**
