### PR TITLE
Add minimal comments to fixManifestLayers

### PR DESCRIPTION
**Pull request by mtrmac**
I have stared at that code often enough now that at least some minimal documentation seems warranted.

This does not really go into why duplicate layers can happen or why it is worth supporting that; the code originates from https://github.com/docker/docker/commit 504e67b867865a2835e8002c01087a2cfd7bfd0e , which does not explain either.

(This will conflict with other PRs, notably #98 . I will rebase as necessary.)

### CODE REVIEW

**Comment by mtrmac** [comment]
Other things worth considering, if we wanted to diverge from the original `docker/docker/distribution` code:

- fail if `len(manifest.FSLayers) != len(manifest.History)`
- fail if `len(manifest.History) == 0`
- fail if, when removing entries with a duplicated ID, we would be removing non-duplicated `FSLayer` entries. (Can this ever happen? If it can, would it happen in this natural way, or would the `FSLayer` duplication perhaps use indexes shifted by one in either direction?)

**Comment by runcom** [comment]
> fail if, when removing entries with a duplicated ID, we would be removing non-duplicated FSLayer entries. (Can this ever happen? If it can, would it happen in this natural way, or would the FSLayer duplication perhaps use indexes shifted by one in either direction?)

Pretty confident this cannot happen :confused:

**Comment by runcom** [comment]
#98 merged, can you rebase?

**Comment by mtrmac** [comment]
Rebased.

**Pull request merged**
