### PR TITLE
Use (git clone --depth=1) to speed up testing

### PR DESCRIPTION
**Pull request by mtrmac**

### CODE REVIEW

**Comment by mtrmac** [comment]
Original: 14m1s:
```
+ git clone https://github.com/docker/distribution.git …
real	0m1.818s
user	0m1.580s
sys	0m0.376s
+ git clone -b v1.5.0-alpha.3 git://github.com/openshift/origin …
…
real	2m34.227s
user	4m18.844s
sys	0m8.144s
```

**Comment by mtrmac** [comment]
New: 12m6s:
```
+ git clone --depth 1 -b v1.5.0-alpha.3 git://github.com/openshift/origin …
…
real	0m8.816s
user	0m2.640s
sys	0m0.856s
```

**Comment by mtrmac** [comment]
This adds `--depth 1` to the checkout of openshift/origin, saving about 700 MB of downloads, and more importantly about 2 minutes of test run time in Travis, both for skopeo and containers/image.

@runcom PTAL.

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
Can we do similar things in CRI-O?

**Comment by mtrmac** [comment]
Probably; are any of the cloned repos _that_ big, though? At least from a quick grep I couldn’t find anything cloning all of Kubernetes, for example.

**Pull request merged**
