### PR TITLE
Vendor containers/image

### PR DESCRIPTION
**Pull request by runcom**
/cc @mtrmac 

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
ok doing the vendoring with my personal branch to see green here

**Comment by runcom** [comment]
@mtrmac updated to vendor my branch and seems ok

**Comment by runcom** [comment]
@mtrmac green here

**Comment by mtrmac** [comment]
ACK, please revendor and merge.

**Pull request merged**
