### PR TITLE
Vendor in mtrmac/image:manifest-list-hotfix

### LINKED ISSUE #416: FATA[0001] can not copy docker://busybox:latest: manifest contains multiple images
In the F26 updates-testing stream for Atomic Host (version 26.120), we saw the following failure:

```
# rpm-ostree status
State: idle
Deployments:
● fedora-atomic:fedora/26/x86_64/testing/atomic-host
                   Version: 26.120 (2017-09-13 05:44:28)
                    Commit: f5cc5928cf44a11b93276c95a3f7ff4eb39a545575b65876cde21426e62d39f1

# rpm -q skopeo
skopeo-0.1.24-1.dev.gita41cd0a.fc26.x86_64

# atomic --debug pull docker.io/busybox
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='docker.io/busybox', profile=False, reg_type=None, storage=None)
Pulling docker.io/library/busybox:latest ...
Executing: /usr/bin/skopeo --policy=/etc/containers/policy.json --debug copy --remove-signatures docker://docker.io/library/busybox:latest docker-daemon:docker.io/library/busybox:latest
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for docker.io/library/busybox:latest 
DEBU[0000] IsRunningImageAllowed for image docker:docker.io/library/busybox:latest 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ err <nil> 
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://registry-1.docker.io/v2/library/busybox/manifests/latest 
DEBU[0000] GET https://registry-1.docker.io/v2/library/busybox/manifests/sha256:030fcb92e1487b18c974784dcc110a93147c9fc402188370fbfd17efabffc6af 
DEBU[0001] Downloading /v2/library/busybox/blobs/sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971 
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971 
DEBU[0001] docker-daemon: Closing tar stream to abort loading 
FATA[0001] can not copy docker://busybox:latest: manifest contains multiple images 

Traceback (most recent call last):
  File "/usr/bin/atomic", line 185, in <module>
    sys.exit(_func())
  File "/usr/lib/python3.6/site-packages/Atomic/pull.py", line 54, in pull_image
    be.pull_image(self.args.image, remote_image_obj, debug=self.args.debug, assumeyes=self.args.assumeyes)
  File "/usr/lib/python3.6/site-packages/Atomic/backends/_docker.py", line 346, in pull_image
    policy_filename=trust.policy_filename)
  File "/usr/lib/python3.6/site-packages/Atomic/util.py", line 429, in skopeo_copy
    return check_call(cmd, env=os.environ)
  File "/usr/lib/python3.6/site-packages/Atomic/util.py", line 197, in check_call
    return subprocess.check_call(cmd, env=env, stdin=stdin, stderr=stderr, stdout=stdout, close_fds=True)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/skopeo', '--policy=/etc/containers/policy.json', '--debug', 'copy', '--remove-signatures', 'docker://docker.io/library/busybox:latest', 'docker-daemon:docker.io
/library/busybox:latest']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/atomic", line 201, in <module>
    sys.exit(e.returncode)
SystemExit: 1
```

If I rollback the system to the previous version of Atomic Host on the updates-testing branch, we see a successful pull:

```
# rpm-ostree status
State: idle
Deployments:
● fedora-atomic:fedora/26/x86_64/testing/atomic-host
                   Version: 26.119 (2017-09-12 00:44:12)
                    Commit: f03426d576f91edb7d6cdcf988a3f8136d458fd15287f975519c87aceb7fd112

  fedora-atomic:fedora/26/x86_64/testing/atomic-host
                   Version: 26.120 (2017-09-13 05:44:28)
                    Commit: f5cc5928cf44a11b93276c95a3f7ff4eb39a545575b65876cde21426e62d39f1

# rpm -q skopeo
skopeo-0.1.23-6.git1bbd87f.fc26.x86_64

# atomic --debug pull docker.io/busybox                                                                                                                                                     
Namespace(_class=<class 'Atomic.pull.Pull'>, assumeyes=False, debug=True, func='pull_image', ignore=False, image='docker.io/busybox', profile=False, reg_type=None, storage=None)
Pulling docker.io/library/busybox:latest ...
Executing: /usr/bin/skopeo --policy=/etc/containers/policy.json --debug copy --remove-signatures docker://docker.io/library/busybox:latest docker-daemon:docker.io/library/busybox:latest
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for docker.io/library/busybox:latest 
DEBU[0000] IsRunningImageAllowed for image docker:docker.io/library/busybox:latest 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ err <nil> 
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://registry-1.docker.io/v2/library/busybox/manifests/latest 
DEBU[0001] Downloading /v2/library/busybox/blobs/sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971 
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971 
DEBU[0001] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json] 
DEBU[0001] ... will first try using the original manifest unmodified 
Copying blob sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e
DEBU[0001] Downloading /v2/library/busybox/blobs/sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e 
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e 
DEBU[0002] Detected compression format gzip             
 0 B / 698.42 KB [-------------------------------------------------------------]DEBU[0002] Using original blob without modification     
DEBU[0002] Sending as tar file sha256:03b1be98f3f9b05cb57782a3a71a44aaf6ec695de5f4f8e6c1058cd42f04953e 
 485.73 KB / 698.42 KB [======================================>----------------]
Copying config sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971
DEBU[0002] No compression detected                      
 0 B / 1.46 KB [---------------------------------------------------------------]DEBU[0002] Using original blob without modification     
DEBU[0002] Sending as tar file sha256:54511612f1c4d97e93430fc3d5dc2f05dfbe8fb7e6259b7351deeca95eaf2971 

Writing manifest to image destination
DEBU[0002] Sending as tar file manifest.json            
Storing signatures
DEBU[0002] docker-daemon: Closing tar stream            
DEBU[0002] docker-daemon: Waiting for status            
DEBU[0002] docker-daemon: sending done, status <nil>    
```

### PR DESCRIPTION
**Pull request by mtrmac**
Fix #416

### CODE REVIEW

**Comment by mtrmac** [comment]
`CopySuite.TestCopyFailsWithManifestList` is expected to fail with this.

**Comment by mtrmac** [comment]
> `CopySuite.TestCopyFailsWithManifestList` is expected to fail with this.

Marked as `ExpectFailure`.

**Comment by mtrmac** [comment]
Description: This vendors in containers/image#344.

**Comment by runcom** [comment]
Not sure this is related:
```
18:58:20 [github.com/projectatomic/skopeo] ‹pr/origin/417› ./skopeo copy docker://redis oci:test                           1 ↵
FATA[0000] Error initializing destination oci:test:: cannot save image with empty image.ref.name
```

**Comment by mtrmac** [comment]
That is https://github.com/containers/image/pull/318 ; use `oci:$somedir:redis` or something like that.

**Pull request merged**
