### PR TITLE
Bump release 0.1.21

### PR DESCRIPTION
**Pull request by runcom**
I'll tag https://github.com/runcom/skopeo-1/commit/0b7315460126b8945fd53f9318a65d7cc8796af1 as v0.1.21

/cc @rhatdan

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
looks like you bumped to 1.22-dev?  Can you change the commit message then please?

**Comment by runcom** [comment]
There are two commits in this PR, https://github.com/projectatomic/skopeo/pull/358/commits/0b7315460126b8945fd53f9318a65d7cc8796af1 this is the one for the release and has correct commit message

**Comment by mtrmac** [comment]
Sure.

**Comment by TomSweeneyRedHat** [comment]
Thanks for the 411 @runcom, I didn't catch the two commits, I thought the second had replaced the first.

**Pull request merged**
