### PR TITLE
Bump and pin containers/storage and containers/image

### PR DESCRIPTION
**Pull request by nalind**
Bump containers/storage, and work around an API change in our vendored copy of containers/image.

### CODE REVIEW

**Comment by mtrmac** [comment]
This bumps containers/storage without updating skopeo’s `vendor.conf`  ??!

(WRT the second commit, it would instead be preferable to temporarily vendor in the https://github.com/containers/image/pull/295 instead of patching generated files, e.g. like #354, and to revert to vendoring from `master` after the c/image PR is merged. This one-liner is trivial enough that the current approach is OK for demonstrating that tests pass.)

After https://github.com/containers/image/pull/295 is merged, please replace this by updating top-level `vendor.conf`, running `vndr` and committing the results.

**Comment by nalind** [comment]
Okay, updated.  We were pulling both storage and image directly from master, so I've set their versions to the current master commit IDs.

**Comment by mtrmac** [comment]
> We were pulling both storage and image directly from master, 

Oops, that was stupid of me. Sorry. In that case, up to you whether you want to pin containers/storage, but leave containers/image at `master`.

**Comment by nalind** [comment]
Okay, reverting the pinning for both.

**Comment by mtrmac** [comment]
:+1: pending tests.

**Comment by runcom** [comment]
will merged after tests :+1:

**Pull request merged**
