### PR TITLE
Bump 0.1.29

### PR DESCRIPTION
**Pull request by runcom**
@rhatdan @mtrmac @nlewo PTAL

### CODE REVIEW

**Comment by runcom** [comment]
I will tag https://github.com/projectatomic/skopeo/pull/486/commits/7add6fc80b0f33406217e7c3361cb711c814f028 as v0.1.29

**Comment by mtrmac** [comment]
ACK, please merge whenever it works for you.

**Comment by rhatdan** [comment]
@runcom I will build packages, but could you create a release doc describing what has changed.

**Comment by nlewo** [comment]
@runcom @mtrmac cool, thanks!

**Comment by rhatdan** [comment]
@runcom lets get a blog published on Monday with the new features. Most are from containers/image

Here is what I put in the skopeo.spec
- Updated containers/image
    docker-archive generates docker legacy compatible images
    Do not create $DiffID subdirectories for layers with no configs
    Ensure the layer IDs in legacy docker/tarfile metadata are unique
    docker-archive: repeated layers are symlinked in the tar file
    sysregistries: remove all trailing slashes
    Improve docker/* error messages
    Fix failure to make auth directory
    Create a new slice in Schema1.UpdateLayerInfos
    Drop unused storageImageDestination.{image,systemContext}
    Load a *storage.Image only once in storageImageSource
    Support gzip for docker-archive files
    Remove .tar extension from blob and config file names
    ostree, src: support copy of compressed layers
    ostree: re-pull layer if it misses uncompressed_digest|uncompressed_size
    image: fix docker schema v1 -> OCI conversion
    Add /etc/containers/certs.d as default certs directory

**Comment by runcom** [comment]
@rhatdan +1

**Pull request merged**
