### PR TITLE
Update for changed images.Type API

### PR DESCRIPTION
**Pull request by mtrmac**
Depends on https://github.com/containers/image/pull/24 .

### CODE REVIEW

**Comment by mtrmac** [comment]
This is a duplicate of #128, with a bit more variable renaming.

… and separating the vendor update commit and the code changes; I suppose I should squash them in the final version so that we don’t have an intermediate broken commit, shouldn’t I?

**Comment by runcom** [comment]
closed #128 - also yes, pls squash so git bisect works fine

**Comment by runcom** [comment]
mmm why isn't Travis using some Docker cache to speed up container build - I should look into it

**Comment by runcom** [comment]
seems like there isn't any good way https://github.com/travis-ci/travis-ci/issues/5358 (unless building and publishing our test docker image, which I don't like). I believe caching can be easily achieved with Jenkins but I don't have clue where to host such a CI infra

**Pull request merged**
