### PR TITLE
Add disclaimer to man page for sign-* commands

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@mtrmac sufficient disclaimer?

**Comment by runcom** [comment]
LGTM - added @mtrmac to collaborators in this repository so he can also merge

**Comment by runcom** [comment]
needs a rebase - then I'll merge

**Comment by jwhonce** [comment]
@runcom @mtrmac rebased.

**Comment by runcom** [comment]
I'm deeply sorry Jhon :( I promise I'll merge after you last rebase this :( :(

**Pull request merged**
