### PR TITLE
Skopeo fetcher

### PR DESCRIPTION
**Pull request by giuseppe**
add the command layers to skopeo. Code copied from cifetch.

### CODE REVIEW

**Comment by runcom** [comment]
Things left to do there:
- sync with upstream docker code (since there's some change in vendor/ here) - I'll do it asap
- add smoke tests under integration/ for the `layer` command - @giuseppe?
- add smoke tests under integration/ for the `inspect` command
- update README for the `layer` command

Current tests pass, thanks @giuseppe - current code is fine right now but it will undergo an heavy refactor to externalize registries' interactions (/cc @vbatts)

**Comment by giuseppe** [comment]
runcom, I resync the file in `vendor/` from `github.com/docker/docker/pkg/homedir/homedir.go`

**Comment by runcom** [comment]
> runcom, I resync the file in vendor/ from github.com/docker/docker/pkg/homedir/homedir.go

this has to be done with `godep` ensuring all deps are fine and in sync

**Comment by giuseppe** [comment]
ok thanks, just I hit this issue when I use `godep`:

```
# github.com/docker/docker/cliconfig
../../docker/docker/cliconfig/config.go:104: authConfig.Email undefined (type types.AuthConfig has no field or method Email)
# github.com/docker/docker/image/v1
../../docker/docker/image/v1/imagev1.go:34: v1Image.ContainerConfig.Cmd.Slice undefined (type strslice.StrSlice has no field or method Slice)
godep: exit status 2
```

**Comment by runcom** [comment]
wait wait, I did a huge mistake, sorry, the script to vendor deps is in `./hack/vendor.sh` sorry about this :cry:

**Comment by giuseppe** [comment]
fixed in the version here :arrow_up:

**Comment by rhatdan** [comment]
I would like to change default skopeo imediately to use the inspect command so that we don't release skopeo into a supported release using the current CLI.  Then you can continue to work on this enhancement to skopeo in time.

**Comment by runcom** [comment]
@rhatdan I'll fix and merge this on top of what @giuseppe did hopefully today or tomorrow

**Pull request closed without merging**
