### PR TITLE
oci: update to image-spec v1 RC5

### PR DESCRIPTION
**Pull request by runcom**
skopeo PR for https://github.com/containers/image/pull/241 (still need to figure c/image PR out, working on it)

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
What's current status?

**Comment by runcom** [comment]
see containers/image#241 @AkihiroSuda

**Comment by runcom** [comment]
Opened https://github.com/projectatomic/skopeo/issues/338 for the latest commit here.

**Comment by mtrmac** [comment]
LGTM pending tests.

**Comment by runcom** [comment]
tests green, but I had to rebase...

**Comment by runcom** [comment]
FYI we're cutting a release shortly

**Pull request merged**
