### PR TITLE
Bump v0.1.23 for OCIv1 support and bug fixes

### PR DESCRIPTION
**Pull request by runcom**
Will tag 1bbd87f4356fed4f21b860b18c50dbe72027b1a0 as v0.1.23

@rhatdan @mtrmac PTAL

### CODE REVIEW

**Comment by mtrmac** [comment]
@runcom Merge https://github.com/projectatomic/skopeo/pull/378 first?

**Comment by mtrmac** [comment]
This LGTM of course

**Comment by runcom** [comment]
> @runcom Merge #378 first?

eheh thanks Miloslav (I was to excited to bump :))

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
