### PR TITLE
Touch up a few tpyos

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Did a quick sweep for typos in README.md per @runcom 's request.

### CODE REVIEW

**Comment by mtrmac** [comment]
LGTM pending tests.

(Perhaps it could be done without the merge commit, though.)

**Comment by TomSweeneyRedHat** [comment]
Yeah, I'm not quite sure what the heck triggered the merge.  I can kill this and try again if you'd like.

**Comment by mtrmac** [comment]
`git rebase origin/master $yourbranch` might be enough to clean this up.

Ultimately, this is not a blocker for me anyway. @runcom may be a bit more demanding :)

**Comment by runcom** [comment]
Yeah, please correctly rebase :)

**Comment by cgwalters** [comment]
Do you guys want to enable our own [PAPR](https://github.com/projectatomic/papr) CI which has homu like atomic/rpm-ostree use?

**Comment by cgwalters** [comment]
Then merges are always gated on tests (and you don't have to wait for them to start a merge), and you don't get small merge commits doubling the size of the git log.

**Comment by TomSweeneyRedHat** [comment]
I love git.  I did 'git rebase -i origin/master' followed by a git push and we're back to github asking for a merge.  Gonna try a few other things.

**Comment by rhatdan** [comment]
@cgwalters I think that would be a good idea.

**Comment by mtrmac** [comment]
We currently run tests on macOS as well. Perhaps we could use both systems, Travis for macOS and PAPR for Linux.

**Pull request closed without merging**
