### PR TITLE
[donotmerge] vendor: update to c/i@copy-obey-destination-compression

### PR DESCRIPTION
**Pull request by cyphar**
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
@runcom The tests pass.

**Comment by runcom** [comment]
you can go ahead and revendor c/image, thanks again

**Comment by cyphar** [comment]
:heart:

**Comment by cyphar** [comment]
@runcom Done.

**Pull request merged**
