### PR TITLE
*: update c/storage

### PR DESCRIPTION
**Pull request by runcom**
/cc @rhatdan 

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
Sure, assuming tests pass. Should `containers/image/vendor.conf` be updated as well?

**Comment by runcom** [comment]
> Sure, assuming tests pass. Should containers/image/vendor.conf be updated as well?

isn't that already pointing to `master`?

**Comment by mtrmac** [comment]
> > Sure, assuming tests pass. Should containers/image/vendor.conf be updated as well?
>
> isn't that already pointing to `master`?

No, in that repo the campaign against using changing branch names was a bit more successful. Hard-codes `29d2c86eadb88a0cbfbbedec8762126a3987d4c3` .

**Comment by runcom** [comment]
> No, in that repo the campaign against using changing branch names was a bit more successful. Hard-codes 29d2c86eadb88a0cbfbbedec8762126a3987d4c3 .

alright I'll change it

**Comment by rhatdan** [comment]
:+1:

**Comment by runcom** [comment]
done, c/image now has correct c/storage version in https://github.com/containers/image/pull/284

**Comment by runcom** [comment]
tests green here also @mtrmac

**Pull request merged**
