### PR TITLE
[donotmerge] vendor: update github.com/containers/image

### PR DESCRIPTION
**Pull request by cyphar**
See projectatomic/libpod#472 and containers/image#427.
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by mtrmac** [comment]
ACK on the `vendor.conf` update.

For the final merge, please use `make vendor` instead of raw `vndr` to preserve the  vendor/github.com/containers/image/docs files.

**Comment by umohnani8** [comment]
@cyphar what is the status on this? I can take over if you aren't getting time to get back to this :)

**Comment by cyphar** [comment]
The problem is that the decompression API in containers/image#427 needs to be changed a fair bit and all of the callers need to be modified. To be honest I completely forgot about this patchset -- I will work on it now...

**Comment by umohnani8** [comment]
@cyphar awesome thanks!

**Comment by mtrmac** [comment]
This was done in #525.  Thanks again!

**Pull request closed without merging**
