### PR TITLE
Fix install command to create directories

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@cgwalters PTAL

**Comment by runcom** [comment]
LGTM, if it works feel free to merge

**Comment by cgwalters** [comment]
:+1:  (At some point we'll get CAHC + PR testing wired up, help always appreciated)

**Comment by mikebrow** [comment]
thx

**Comment by runcom** [comment]
@rhatdan, can you rebase? There's a merge commit which isn't supposed to be here

**Comment by cgwalters** [comment]
I don't see a merge commit in this PR?

**Comment by runcom** [comment]
He did remove it now since there's a commit below my comment,  merging

**Pull request merged**
