### PR TITLE
add progress bars during copy

### PR DESCRIPTION
**Pull request by runcom**
@mtrmac PTAL since this is vendoring other stuff not related to progress bars.

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
If we have progress bars, should we cut a new version for Rawhide/F25, so people can play with it.

**Comment by runcom** [comment]
> If we have progress bars, should we cut a new version for Rawhide/F25, so people can play with it.

@rhatdan yep, I'm going to re-vendor this into skopeo and cut a new 0.1.15 tag in skopeo, @mtrmac ok?

**Comment by mtrmac** [comment]
Sure, there have been enough bugfixes. (But still without docker-daemon I assume?)

**Comment by runcom** [comment]
> (But still without docker-daemon I assume?)

yeah, I'll tag from master

**Pull request merged**
