### PR TITLE
Add a policy evaluation library

### PR DESCRIPTION
**Pull request by mtrmac**
This is now mostly ready for review; in particular the public API structure of `PolicyContext`, and the internal abstraction of `PolicyRequirement` and `PolicyReferenceMatch`, are done.

The one thing I still want to get done before merging is to eliminate duplication between `signature.go` and `policy_eval_signedby.go`.

See individual commit messages for a little more detailed descriptions.

### CODE REVIEW

**Comment by mtrmac** [comment]
(Depends on #75, which will also be affected by the `signature.go` duplicate elimination; I will rebase as necessary.)

**Comment by mtrmac** [comment]
> The one thing I still want to get done before merging is to eliminate duplication between `signature.go` and `policy_eval_signedby.go`.

Done.

Calling this finished, ready for review.

**Comment by runcom** [comment]
LGTM feel free to merge it (does it needs a rebase?)

**Comment by mtrmac** [comment]
Yeah, this included #75 . Will merge after tests, thanks!

**Pull request merged**
