### PR TITLE
DO NOT MERGE: Update docker/docker dependencies.

### PR DESCRIPTION
**Pull request by mgoltzsche**
Required due to pending dependency update in containers/image.

This pull request should be merged only after containers/image#446 has been merged.

I applied the updates from containers/image#446 to `vendor.conf`:
```
github.com/docker/docker
github.com/containerd/continuity
github.com/docker/go-connections
```
and called `make vendor` afterwards.

Until containers/image#446 is merged this PR's containers/image entry in `vendor.conf` points to containers/image#446's branch. After the latter has been merged I ll switch the containers/image dependency in this branch back to containers/image `master` to make this PR mergeable.

EDIT: removed unnecessary dependency updates and mentioned changed merge order.

Signed-off-by: Max Goltzsche <max.goltzsche@gmail.com>

### CODE REVIEW

**Comment by mgoltzsche** [comment]
I just added the updated vendor files of containers/image here to make sure travis build succeeds and ran the integration test but it fails unfortunately at the tls verification option. I ll have another look...

**Comment by mgoltzsche** [comment]
Fixed now: the error message assertion in one of the integration tests had to be adjusted.

**Comment by mtrmac** [comment]
Thanks; see https://github.com/containers/image/pull/446#issuecomment-390375031 , why are some of the versions going backward?

**Comment by mgoltzsche** [comment]
See [comment in #446](https://github.com/containers/image/pull/446#issuecomment-391167204)

**Comment by mtrmac** [comment]
Carried in #512.  Thanks again!

**Pull request closed without merging**
