### PR TITLE
Implement a lookaside storage for signatures of images in Docker registries

### PR DESCRIPTION
**Pull request by mtrmac**
This vendors in unmerged https://github.com/containers/image/pull/52 and updates the API usage.  See the documentation in that PR for more details.

### CODE REVIEW

**Comment by mtrmac** [comment]
TODO? This would very much benefit from an integration test.

**Comment by mtrmac** [comment]
Rebased, now depends only on https://github.com/containers/image/issues/52 .  Still would benefit from an integration test.

**Comment by mtrmac** [comment]
Tests now exist (in #177), but depend on pushing to tags in Docker registries.  But with a hackish way to do that, they pass; so this PR + the containers/image implementation is ready for review and merging.

**Comment by mtrmac** [comment]
Updated per https://github.com/projectatomic/atomic/issues/594 , adds `--registries.d` to allow integration testing now that `$ATOMIC_CONF` is not used.

Integration tests are still in #177 and don’t work against `master`, (they need push to Docker tags), but work well enough to demonstrate the lookaside works.

@runcom low-priority ping

**Comment by runcom** [comment]
@mtrmac https://github.com/projectatomic/skopeo/pull/170/commits/91ebebce1388442b0f301aea6fadc38995cda3bb LGTM (I LGTM'ed the vendor in containers/image also)

**Pull request merged**
